services:
  postgres:
    build:
      context: './postgres'
      dockerfile: 'Dockerfile'
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
       - '${DATA_PATH_HOST}:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT}:5432'
  
  pgadmin:
    build:
      context: './pgadmin4'
      dockerfile: 'Dockerfile'
      args:
        PG_ADMIN_VERSION: ${PG_ADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT}:80'

volumes:
  pgadmin-data: