#User defined
user:
  postgres_version:
    label:
      PostgreSQL version
    hint:
      Select PostgreSQL version
    type:
      select
    values:
      - "17"
      - "16"
      - "15"
      - "14"
      - "13"
    target:
      POSTGRES_VERSION

  pgadmin_version:
    label:
      pgAdmin version
    hint:
      Select pgAdmin version
    type:
      select
    values:
      - "9.2"
      - "9.1"
      - "9.0"
      - "8.14"
      - "7.8"
      - "6.21"
    target:
      PG_ADMIN_VERSION

#System defaults
system:
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      PGADMIN_PORT
    others:
      - POSTGRES_PORT

